### PR TITLE
Corrected unit test from HELP to FAILED

### PR DESCRIPTION
**Pull request by davidwhitman**
Looks like this test was meant to use Fail, not Help, from the Assert statements.

### CODE REVIEW

**Comment by Mauin** [comment]
Created #11 because that's probably failing the build here. 

As for the changes. HELP and FAILED will both lead to the same result in the test. Seems to me that this is more of a copy/paste error when those tests were written so the Assert statements state FAILED instead of HELP.

**Comment by davidwhitman** [comment]
Looks like something's out of date in gradle - unrelated to this PR.

**Comment by davidwhitman** [comment]
Ah ok, if that's the case then this can be closed. I thought that Failed was the desired call.

Thanks for this library, by the way. This is the kind of stuff that should be included with the Android SDK by default (not the Rx, but the "here's an easy way to use this with all of the defaults" part).

**Comment by Mauin** [comment]
Merged #11 so this build should now work.

Feel free to correct the Assert statements, but I'd leave it at the HELP call.

**Pull request closed without merging**
